### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by robla** [brainbuz/Vote-Count#13]
The "About" section for [brainbuz/Vote-Count](https://github.com/brainbuz/Vote-Count) says:

> A toolkit for alternative voting methods. Initially to support Rankled and Range Ballots for IRV, Boorda, and Pairwise/Condorcet. Future support planned Multi-member methods.

Those are cute misspellings of "Borda" and "Ranked" if you're trying to make fun of those methods, but are bad for SEO.  If you want people to find this library, you should probably spell the methods properly.  There's also a spot where "Kemeny" is misspelled which should also be fixed.

**Comment by brainbuz** [comment]
All typos are typos. They'll be fixed in release 2.01. I also re-organized the documentation a little bit.
